# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('container_name', models.CharField(max_length=100)),
                ('container_ip_address', models.CharField(max_length=15)),
                ('container_port', models.IntegerField(default=0)),
            ],
        ),
    ]
